### PR TITLE
MIME type, double-quotes

### PR DESCRIPTION
**Pull request by 355over113**

### CODE REVIEW

**Comment by Bergenfrundt** [comment]
The div class "fontfam" is meant to envelop the whole document so i can change the font using CSS. You closed the div right where it starts.

**Comment by 355over113** [comment]
You should still change the MIME type and single-quotes to double-quotes. Also, if you want to target the entire document, select the body like so:

    body {
        font-family: sans-serif;
    }

**Comment by Bergenfrundt** [comment]
Fair enough. Open another pull that changes those, and removes the fontfam div class. I'll do the changing of the font. 

Also, that href at the start that links to google is a link for the font open sans if you were wondering.

**Comment by 355over113** [comment]
I know. I've used Google Fonts before.

**Comment by Bergenfrundt** [comment]
I'm closing this now. Make a new pull with the changes outlined in my last comment. I've already pushed a change to change the font css to target the Body rather than targeting the fontfam div class.

**Pull request merged**
